name: my_workout
description: App para a listagem e cadastro de exericios fisicos.


version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cloud_firestore:
  firebase_auth:
  firebase_core:
  firebase_storage: ^10.3.1
  brasil_fields:
  curved_navigation_bar:
  image_picker:
  validadores: ^1.0.5




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/App.ttf

  uses-material-design: true


  assets:
    - assets/imagens/black/23.jpg
